### ISSUE TITLE
Update CSS to left justify table captions

### ISSUE THREAD

**Issue by slochower** [greenelab/manubot-rootstock#130]
I suggest changing the CSS to left justify table captions, since the main text is left justified and the figure captions are as well. For example, only the table caption in this document is center justified: https://greenelab.github.io/meta-review/v/b8eeea542ce238bbcaf2023add2aecb86ef726bd/

It's not immediately obvious where to change the CSS to accomplish this, but I didn't look thoroughly.

**Comment by agitter** [comment]
That's a good idea.  It should be consistent with the figures.

**Comment by dhimmel** [comment]
Yeah figure formatting is NOT GOOD. I made some changes for the [Project Rephetio Manuscript](https://git.dhimmel.com/rephetio-manuscript/) in https://github.com/dhimmel/rephetio-manuscript/commit/c78f9ad09d063982a1668a285b2fdf7b14c9df05. This includes the caption fix:

```css
/**
* Make caption text left-aligned (previousely it was centered).
*/
caption {
    text-align: left;
}
```

**Comment by slochower** [comment]
Nice, happy to take a look at the PR. This has motivated me to find  my tweak for centering non-full-width images mentioned in https://github.com/greenelab/manubot-rootstock/issues/55#issuecomment-398908740.

**Comment by dhimmel** [comment]
We can also set the `caption-side` property to `top` or `bottom` to specify where the caption should go. `top` is default and current behavior. PeerJ uses top for tables. However, `bottom` would match the figure behavior. Preferences?

**Comment by vsmalladi** [comment]
I prefer top.

**Comment by slochower** [comment]
I prefer bottom, but I think most journals have it at top. 

Consider changing
https://github.com/greenelab/manubot-rootstock/blob/9aec6f5c2eeca9002a5ce4dc06808fc2fbec24f3/webpage/github-pandoc.css#L282-L284
to

```css
img {
  display:block;
  margin-left:auto;
  margin-right:auto;
  max-width:100%
}
```
 to center non-full-width images.
