### ISSUE TITLE
Heading numbering

### ISSUE THREAD

**Issue by multimeric** [greenelab/manubot-rootstock#441]
I wanted to have heading numbering, like this:
![image](https://user-images.githubusercontent.com/5019367/138029578-368d44ec-e7b0-4374-b94e-7f25dad93e34.png)

Now, I wrote some CSS that solves this problem (at least for 2 subheadings, although it can be extended to include more). I'm wondering if I could push it upstream, either into:

* The base theme, but locked behind an HTML class so that users can trivially add it, or
* Into the docs so that people can easily find a way to add numbering

The CSS in question is:

```css
  body {
    counter-reset: heading 1;
    counter-reset: subheading 1;
  }

  h2:before {
	content: counter(heading)". ";
  }

  h2 {
    counter-reset: subheading;
    counter-increment: heading;
  }

  h3:before {
    counter-increment: subheading;
    content: counter(heading) "." counter(subheading) ". ";
  }
```
