### ISSUE TITLE
Setting up manubot-rootstock for GitLab with GitLab-CI

### ISSUE THREAD

**Issue by RaoOfPhysics** [greenelab/manubot-rootstock#88]
Just a suggestion: https://about.gitlab.com/features/gitlab-ci-cd/ :)

**Comment by dhimmel** [comment]
@RaoOfPhysics I do think it would be a major improvement to remove dependencies on proprietary platforms (GitHub & Travis CI). Luckily, switching providers shouldn't be too difficult and can be done at any point in the future. The main reason we chose GitHub is for its large user base and its familiarity to many developers.

If someone wants to port the project to GitLab, that would be the next step. It's not high on my priority list, since GitHub and Travis have been working well. However, we should periodically re-evaluate our thinking here.

**Comment by vsmalladi** [comment]
We use Gitlab on our servers and have looked into this. I can take a look further on what it would take to support GitLab.

**Comment by slochower** [comment]
I started a half-hearted attempt to setup `manubot` with GitLab. I ran out of time to get it working and it's not a high priority for me, but by leaving a breadcrumb trail maybe someone else who's interested will pick up and get it to work.

1. Add `.gitlab.yaml` to enable CI on GitLab.
```
image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - ci/cache
    
before_script:
  - python -V               # Print out python version for debugging
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.3.31-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
  - apt-get update
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - apt-get install gettext-base

run:
  script:
  - conda env create --quiet --file build/environment.yml
  - source activate manubot
  - sh build/build.sh
 
after_script:
  - sh ci/deploy.sh
  
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r webpage .public
  - mv .public public
  artifacts:
    paths:.
    - public
  only:
  - master
```

The locale and language stuff is necessary, otherwise there will be hard-to-pin-down Python ASCII errors. `gettext-base` is necessary for `envsubst`. The `conda` stuff should probably be `before_script`, but I didn't mess around with it. The last section `pages` is for [GitLab pages](https://docs.gitlab.com/ee/user/project/pages/), not surprisingly.  I *don't* think copying the `webpage` directory to `public` is the best thing to do --  I think that pushing to a new branch (as we already do on GitHub) and then doing a pull into `public` is probably better. But again, I didn't have time to get this working and copying was a quick troubleshooting step.

2. Modify `deploy.sh` with GitLab environmental variables.
```
# Exit on errors
set -o errexit

# Add commit hash to the README
export OWNER_NAME=$CI_PROJECT_NAMESPACE
export REPO_NAME=$CI_PROJECT_NAME
envsubst < webpage/README.md > webpage/README-complete.md
mv webpage/README-complete.md webpage/README.md

# Fetch and create gh-pages and output branches
# Travis does a shallow and single branch git clone
git remote set-branches --add origin gh-pages output
git fetch origin gh-pages:gh-pages output:output

# Configure versioned webpage
python build/webpage.py \
  --checkout=gh-pages \
  --version=$CI_COMMIT_REF

# Generate OpenTimestamps
ots stamp \
  webpage/v/$CI_COMMIT_REF/index.html \
  webpage/v/$CI_COMMIT_REF/manuscript.pdf

# Commit message
MESSAGE="\
`git log --max-count=1 --format='%s'`

This build is based on
https://github.com/$CI_PROJECT_PATH/commit/$CI_COMMIT_REF.
"

git \
  --push \
  --branch=output \
  --message="$MESSAGE" \
  output

# Deploy the webpage directory to gh-pages
git \
  --follow-links \
  --push \
  --branch=gh-pages \
  --message="$MESSAGE" \
  webpage
```
